### PR TITLE
Update AndroidManifest.xml

### PR DESCRIPTION
**Pull request by aldocano**
Added permissions.

### CODE REVIEW

**Review by TUSHARZ — CHANGES_REQUESTED** [review]
Good Work , 
Try to implement this dynamically , 
I mean you have seen apps asking permissions on runtime that it wants to acces your camera or storage,
Try to implement that

**Comment by aldocano** [comment]
But what are you asking is runtime persmissions, available on api 23 and above. Your app supports only lollipop.

**Comment by TUSHARZ** [comment]
That's what i am trying to do ,
Implement runtime permissions so that it could support api 23 and above

**Comment by aldocano** [comment]
someone else did it, you can merge his code. You have to explain better next time.

**Comment by TUSHARZ** [comment]
Nope , 
he only implemented reading permissions and forgot to implement writing permissions so i am still on hold , 
You can still do it if you want..
Sorry , i will keep in mind to explain the issue more clearly..

**Pull request closed without merging**
